INSERT INTO `media` (`media_id`, `name`, `artist`, `description`, `genre`, `year`, `type`, `state`, `price`, `quantity`, `language`, `last_changed`) 
VALUES (NULL, 'Franz Ferdinand', 'Franz Ferdinand', '', 'Alternative Rock', '2004', 'CD', 'New', '9.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'You Could Have It So Much Better', 'Franz Ferdinand', '', 'Alternative Rock', '2005', 'CD', 'New', '9.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Tonight', 'Franz Ferdinand', '', 'Alternative Rock', '2009', 'CD', 'New', '9.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Right Thoughts Right Words Right Action', 'Franz Ferdinand', '', 'Alternative Rock', '2013', 'CD', 'New', '10.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Showbiz', 'Muse', '', 'Alternative Rock', '1999', 'CD', 'New', '15.99', '20', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Origin of Symmetry', 'Muse', '', 'Alternative Rock', '2001', 'CD', 'New', '15.99', '20', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Absolution', 'Muse', '', 'Alternative Rock', '2003', 'CD', 'New', '15.99', '20', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Black Holes and Revelations', 'Muse', '', 'Alternative Rock', '2006', 'CD', 'New', '15.99', '20', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'The Resistance', 'Muse', '', 'Alternative Rock', '2009', 'CD', 'New', '15.99', '20', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'The 2nd Law', 'Muse', '', 'Alternative Rock', '2012', 'CD', 'New', '15.99', '20', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Drones', 'Muse', '', 'Alternative Rock', '2015', 'CD', 'New', '16.99', '20', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'The Verve', 'The Verve', '', 'Britpop', '1992', 'CD', 'Used', '20.99', '1', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'A Storm in Heaven', ' The Verve', '', 'Britpop', '1993', 'CD', 'Used', '20.99', '1', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'A Northern Soul', 'The Verve', '', 'Britpop', '1995', 'CD', 'New', '15.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Urban Hymns', 'The Verve', '', 'Britpop', '1997', 'CD', 'New', '15.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'No Come Down', 'The Verve', '', 'Britpop', '2002', 'CD', 'New', '15.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'This is Music', 'The Verve', '', 'Britpop', '2004', 'CD', 'New', '15.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Forth', 'The Verve', '', 'Britpop', '2008', 'CD', 'New', '15.99', '10', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Please Please Me', 'The Beatles', '', 'Rock', '1963', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'With The Beatles', 'The Beatles', '', 'Rock', '1964', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'A Hard Days Night', 'The Beatles', '', 'Rock', '1964', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Beatles For Sale', 'The Beatles', '', 'Rock', '1964', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Help!', 'The Beatles', '', 'Rock', '1965', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Rubber Soul', 'The Beatles', '', 'Rock', '1965', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Revolver', 'The Beatles', '', 'Rock', '1966', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Sgt. Peppers Lonely Hearts Club Band', 'The Beatles', '', 'Rock', '1967', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'The White Album', 'The Beatles', '', 'Rock', '1968', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Abbey Road', 'The Beatles', '', 'Rock', '1969', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Yellow Submarine', 'The Beatles', '', 'Rock', '1969', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP),
	   (NULL, 'Let It Be', 'The Beatles', '', 'Rock', '1970', 'Vinyl', 'Used', '29.99', '5', 'English', CURRENT_TIMESTAMP)